version: '2'
services:
  php:
    build: ./docker/php/
    environment:
      - DEVELOPER_PORT=${XDEBUG_PORT}
      - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
      - XDEBUG_CONFIG=${XDEBUG_CONFIG}
      - DEVELOPER_HOST=${DEVELOPER_HOST}
      - PROJECT_ENV=${PROJECT_ENV}
      - TIMEZONE=Europe/Kiev
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
      - ${PATH_WORK}:/var/www
    working_dir: /var/www

  nginx:
    image: nginx:1.11
    depends_on:
      - php
    volumes_from:
      - php
    volumes:
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - ${PORT_NGINX}

  mysql:
    image: mysql:5.7
    volumes_from:
      - mysqldata
    ports:
      - ${PORT_MYSQL}
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

  mysqldata:
    image: debian:jessie
    volumes:
      - /var/lib/mysql
